# Generated by Django 5.2.8 on 2025-11-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='candidate_resumes/')),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('projects_found', models.JSONField(blank=True, default=list)),
                ('education', models.TextField(blank=True, null=True)),
                ('ai_score', models.IntegerField(default=0)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='jobs.job')),
            ],
        ),
    ]
