# Generated by Django 5.2.8 on 2025-11-15 10:09

import candidates.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateresume',
            name='applied_at',
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='education',
            field=models.TextField(blank=True, default='l'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidateresume',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=candidates.models.resume_upload_path),
        ),
    ]
