# Generated by Django 5.2.8 on 2025-11-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_remove_candidateresume_applied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresume',
            name='shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
